# Generated by Django 4.2.7 on 2025-07-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_notice_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="advnotice_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Show this notice in the modal if active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertisement/Notice",
                "verbose_name_plural": "Advertisements/Notices",
                "ordering": ["-created_at"],
            },
        ),
    ]
