# Generated by Django 4.2.7 on 2025-07-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_galleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherstaff",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
