# Generated by Django 4.2.7 on 2025-07-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_teacherstaff_designation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("teaching", "Teaching Staff"),
                            ("non_teaching", "Non-Teaching Staff"),
                        ],
                        default="teaching",
                        max_length=20,
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="staff_photos/"),
                ),
                ("bio", models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name="TeacherStaff",
        ),
    ]
