# Generated by Django 4.2.7 on 2025-07-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_staff_delete_teacherstaff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryimage",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.RenameField(
            model_name="download",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="executivemessage",
            old_name="photo",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="galleryimage",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="executivemessage",
            name="role",
        ),
        migrations.AddField(
            model_name="download",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("forms", "Forms"),
                    ("documents", "Documents"),
                    ("brochures", "Brochures"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="download",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="download",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="download",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="executivemessage",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="executivemessage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="executivemessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("events", "Events"),
                    ("activities", "Activities"),
                    ("facilities", "Facilities"),
                    ("students", "Students"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
